### ISSUE TITLE
URL issue for /ewhc/admin/2019/3242

### ISSUE THREAD

**Issue by KarDjen** [nationalarchives/ds-caselaw-public-ui#1376]
There's a mismatch between url /ewhc/admin/2019/3242 and the court case that it displays which is supposed to be  '[2022] UKUT 28 (LC)' instead of 'Compton PC v Guildford BC[2019] EWHC 3242 (Admin)'. 

hope it helps.

**Comment by jacksonj04** [comment]
@KarDjen just to let you know that this judgment's URL has now been fixed, and we're working through the backlog of similar documents with mismatched URLs. Thanks for the bug report!
