### ISSUE TITLE
Atom feed court filter for `ewhc` results in server error

### ISSUE THREAD

**Issue by jcsrb** [nationalarchives/ds-caselaw-public-ui#1520]
With the current Atom feed i noticed that only court+subdivision is working but not court directly

using just `ewhc` doesn't work and yields a “Server Error”
❌ https://caselaw.nationalarchives.gov.uk/atom.xml?court=ewhc 

where the example from the docs works returns the expected atom feed
✅ https://caselaw.nationalarchives.gov.uk/atom.xml?court=ewhc/fam

related documentation
https://nationalarchives.github.io/ds-find-caselaw-docs/public#tag/Reading-documents/operation/atomFeed

is this a bug?

**Comment by jacksonj04** [comment]
Hi @jcsrb,

Thanks for flagging this to us. I can confirm that this is a bug, and we're working on a fix right now, hopefully to ship in the next couple of days.
