### ISSUE TITLE
Atom API. Bug with parameter page greater than 2024

### ISSUE THREAD

**Issue by alexfromk** [nationalarchives/ds-caselaw-public-ui#357]
Hello, 
 we are trying to work with National Archives API, with service Atom.
 
We got the data by requests like this:
https://caselaw.nationalarchives.gov.uk/atom.xml?page=1&order=-date
All work fine with parameter "page" since 1 to 2024, but when page became greater 2024, service return HTTP 504.
For example,
GET https://caselaw.nationalarchives.gov.uk/atom.xml?page=2025&order=-date
response with http 504.
If it is possible, to fix this bug.

With best regards. Alex Kononenko

**Comment by dragon-dxw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🐳Response to Atom feed pages above 2024 HTTP 504 error](https://trello.com/c/o5KlKzkN/976-%F0%9F%90%B3response-to-atom-feed-pages-above-2024-http-504-error)

**Comment by alexfromk** [comment]
> 

Hi, thank you very much. 
I tested it, paging above 2024  work fine.
 Alex Kononenko
